### ISSUE TITLE
Improve the UI of the Hero section

### ISSUE THREAD

**Issue by mishrashree18** [zairza-cetb/SPARK#5]
![Screenshot from 2022-10-03 11-40-41](https://user-images.githubusercontent.com/65803594/193511648-48ec6a15-48e8-4e57-9996-9b355087c1b5.png)
UI of this section is to be improved.
Note: The color scheme and font style needs to be same as in all pages.

**Comment by amitmishra11** [comment]
@mishrashree18  can you please elaborate what changes do you need
Like what if I add hover effects in this section along with some minor changes

**Comment by mishrashree18** [comment]
@amitmishra11 it would be great if you could give it a complete makeover by changing the layout, adding hover effects, making the heading and texts in paragraph more attractive based on your creativity and improving the design of the navbar. Along with that you can add your minor changes too. Would you like to work on this issue?

**Comment by amitmishra11** [comment]
@mishrashree18 yeah please assign me the issue I would try to improve the UI

**Comment by mishrashree18** [comment]
@amitmishra11 I have assigned you the issue, you can start working now.
